/**
 * SINH TỰ ĐỘNG — đừng sửa tay, chạy lại sẽ mất.
 *
 *   npm run sync:warehouse
 *
 * Nguồn: trang quản trị (Laravel). Sửa sản phẩm bên đó rồi chạy lại lệnh trên.
 */

import type { Seed } from "./data";

export const shopeeSeeds: Seed[] = [
  {
    slug: "ao-khoac-jean-unisex",
    name: "Áo khoác jean unisex",
    category: "Áo khoác",
    audience: "Unisex",
    price: 459000,
    image: "/images/placeholder.svg",
    hoverImage: "/images/placeholder.svg",
    isNew: true,
    rating: 0,
    reviews: 0,
    description: "Áo khoác jean unisex - hàng thiết kế, chất liệu denim.",
    details: [
      "Chất liệu: Denim",
      "Thương hiệu: Phương Lê",
      "Có size: S, M, L, XL",
      "Màu: Đen, Trắng, Be",
    ],
    colors: [
      {"name":"Đen","hex":"#1c1714"},
      {"name":"Trắng","hex":"#f0e7d8"},
      {"name":"Be","hex":"#d8c4a4"},
    ],
    sizes: ["S","M","L","XL"],
    variants: [
      {"id":"37","color":"Đen","size":"S","stock":25},
      {"id":"38","color":"Trắng","size":"S","stock":28},
      {"id":"39","color":"Be","size":"S","stock":25},
      {"id":"40","color":"Đen","size":"M","stock":8},
      {"id":"41","color":"Trắng","size":"M","stock":22},
      {"id":"42","color":"Be","size":"M","stock":25},
      {"id":"43","color":"Đen","size":"L","stock":21},
      {"id":"44","color":"Trắng","size":"L","stock":0},
      {"id":"45","color":"Be","size":"L","stock":19},
      {"id":"46","color":"Đen","size":"XL","stock":22},
      {"id":"47","color":"Trắng","size":"XL","stock":0},
      {"id":"48","color":"Be","size":"XL","stock":3},
    ],
  },
  {
    slug: "ao-so-mi-lua-tay-dai",
    name: "Áo sơ mi lụa tay dài",
    category: "Áo sơ mi",
    audience: "Unisex",
    price: 299000,
    image: "/images/placeholder.svg",
    hoverImage: "/images/placeholder.svg",
    isNew: true,
    rating: 0,
    reviews: 0,
    description: "Áo sơ mi lụa tay dài - hàng thiết kế, chất liệu lụa.",
    details: [
      "Chất liệu: Lụa",
      "Thương hiệu: Phương Lê",
      "Có size: S, M, L, XL",
      "Màu: Đen, Trắng, Be",
    ],
    colors: [
      {"name":"Đen","hex":"#1c1714"},
      {"name":"Trắng","hex":"#f0e7d8"},
      {"name":"Be","hex":"#d8c4a4"},
    ],
    sizes: ["S","M","L","XL"],
    variants: [
      {"id":"25","color":"Đen","size":"S","stock":0},
      {"id":"26","color":"Trắng","size":"S","stock":10},
      {"id":"27","color":"Be","size":"S","stock":27},
      {"id":"28","color":"Đen","size":"M","stock":17},
      {"id":"29","color":"Trắng","size":"M","stock":16},
      {"id":"30","color":"Be","size":"M","stock":28},
      {"id":"31","color":"Đen","size":"L","stock":10},
      {"id":"32","color":"Trắng","size":"L","stock":9},
      {"id":"33","color":"Be","size":"L","stock":27},
      {"id":"34","color":"Đen","size":"XL","stock":11},
      {"id":"35","color":"Trắng","size":"XL","stock":5},
      {"id":"36","color":"Be","size":"XL","stock":4},
    ],
  },
  {
    slug: "ao-thun-cotton-basic",
    name: "Áo thun cotton basic",
    category: "Áo thun",
    audience: "Unisex",
    price: 159000,
    image: "/images/placeholder.svg",
    hoverImage: "/images/placeholder.svg",
    isNew: true,
    rating: 0,
    reviews: 0,
    description: "Áo thun cotton basic - hàng thiết kế, chất liệu cotton 100%.",
    details: [
      "Chất liệu: Cotton 100%",
      "Thương hiệu: Phương Lê",
      "Có size: S, M, L, XL",
      "Màu: Đen, Trắng, Be",
    ],
    colors: [
      {"name":"Đen","hex":"#1c1714"},
      {"name":"Trắng","hex":"#f0e7d8"},
      {"name":"Be","hex":"#d8c4a4"},
    ],
    sizes: ["S","M","L","XL"],
    variants: [
      {"id":"1","color":"Đen","size":"S","stock":7},
      {"id":"2","color":"Trắng","size":"S","stock":5},
      {"id":"3","color":"Be","size":"S","stock":20},
      {"id":"4","color":"Đen","size":"M","stock":8},
      {"id":"5","color":"Trắng","size":"M","stock":6},
      {"id":"6","color":"Be","size":"M","stock":15},
      {"id":"7","color":"Đen","size":"L","stock":2},
      {"id":"8","color":"Trắng","size":"L","stock":10},
      {"id":"9","color":"Be","size":"L","stock":3},
      {"id":"10","color":"Đen","size":"XL","stock":21},
      {"id":"11","color":"Trắng","size":"XL","stock":30},
      {"id":"12","color":"Be","size":"XL","stock":7},
    ],
  },
  {
    slug: "ao-thun-oversize-form-rong",
    name: "Áo thun oversize form rộng",
    category: "Áo thun",
    audience: "Unisex",
    price: 189000,
    image: "/images/placeholder.svg",
    hoverImage: "/images/placeholder.svg",
    isNew: true,
    rating: 0,
    reviews: 0,
    description: "Áo thun oversize form rộng - hàng thiết kế, chất liệu cotton pha.",
    details: [
      "Chất liệu: Cotton pha",
      "Thương hiệu: Phương Lê",
      "Có size: S, M, L, XL",
      "Màu: Đen, Trắng, Be",
    ],
    colors: [
      {"name":"Đen","hex":"#1c1714"},
      {"name":"Trắng","hex":"#f0e7d8"},
      {"name":"Be","hex":"#d8c4a4"},
    ],
    sizes: ["S","M","L","XL"],
    variants: [
      {"id":"13","color":"Đen","size":"S","stock":9},
      {"id":"14","color":"Trắng","size":"S","stock":22},
      {"id":"15","color":"Be","size":"S","stock":16},
      {"id":"16","color":"Đen","size":"M","stock":10},
      {"id":"17","color":"Trắng","size":"M","stock":13},
      {"id":"18","color":"Be","size":"M","stock":10},
      {"id":"19","color":"Đen","size":"L","stock":10},
      {"id":"20","color":"Trắng","size":"L","stock":0},
      {"id":"21","color":"Be","size":"L","stock":30},
      {"id":"22","color":"Đen","size":"XL","stock":23},
      {"id":"23","color":"Trắng","size":"XL","stock":26},
      {"id":"24","color":"Be","size":"XL","stock":14},
    ],
  },
  {
    slug: "dam-du-tiec-dang-xoe",
    name: "Đầm dự tiệc dáng xòe",
    category: "Đầm dự tiệc",
    audience: "Unisex",
    price: 750000,
    image: "/images/placeholder.svg",
    hoverImage: "/images/placeholder.svg",
    isNew: true,
    rating: 0,
    reviews: 0,
    description: "Đầm dự tiệc dáng xòe - hàng thiết kế, chất liệu voan lụa.",
    details: [
      "Chất liệu: Voan lụa",
      "Thương hiệu: Phương Lê",
      "Có size: S, M, L, XL",
      "Màu: Đen, Trắng, Be",
    ],
    colors: [
      {"name":"Đen","hex":"#1c1714"},
      {"name":"Trắng","hex":"#f0e7d8"},
      {"name":"Be","hex":"#d8c4a4"},
    ],
    sizes: ["S","M","L","XL"],
    variants: [
      {"id":"97","color":"Đen","size":"S","stock":27},
      {"id":"98","color":"Trắng","size":"S","stock":29},
      {"id":"99","color":"Be","size":"S","stock":23},
      {"id":"100","color":"Đen","size":"M","stock":18},
      {"id":"101","color":"Trắng","size":"M","stock":25},
      {"id":"102","color":"Be","size":"M","stock":20},
      {"id":"103","color":"Đen","size":"L","stock":22},
      {"id":"104","color":"Trắng","size":"L","stock":28},
      {"id":"105","color":"Be","size":"L","stock":30},
      {"id":"106","color":"Đen","size":"XL","stock":23},
      {"id":"107","color":"Trắng","size":"XL","stock":22},
      {"id":"108","color":"Be","size":"XL","stock":26},
    ],
  },
  {
    slug: "quan-jean-ong-suong",
    name: "Quần jean ống suông",
    category: "Quần jean",
    audience: "Unisex",
    price: 389000,
    image: "/images/placeholder.svg",
    hoverImage: "/images/placeholder.svg",
    isNew: true,
    rating: 0,
    reviews: 0,
    description: "Quần jean ống suông - hàng thiết kế, chất liệu denim co giãn.",
    details: [
      "Chất liệu: Denim co giãn",
      "Thương hiệu: Phương Lê",
      "Có size: S, M, L, XL",
      "Màu: Đen, Trắng, Be",
    ],
    colors: [
      {"name":"Đen","hex":"#1c1714"},
      {"name":"Trắng","hex":"#f0e7d8"},
      {"name":"Be","hex":"#d8c4a4"},
    ],
    sizes: ["S","M","L","XL"],
    variants: [
      {"id":"49","color":"Đen","size":"S","stock":7},
      {"id":"50","color":"Trắng","size":"S","stock":12},
      {"id":"51","color":"Be","size":"S","stock":21},
      {"id":"52","color":"Đen","size":"M","stock":21},
      {"id":"53","color":"Trắng","size":"M","stock":17},
      {"id":"54","color":"Be","size":"M","stock":11},
      {"id":"55","color":"Đen","size":"L","stock":14},
      {"id":"56","color":"Trắng","size":"L","stock":10},
      {"id":"57","color":"Be","size":"L","stock":17},
      {"id":"58","color":"Đen","size":"XL","stock":10},
      {"id":"59","color":"Trắng","size":"XL","stock":3},
      {"id":"60","color":"Be","size":"XL","stock":2},
    ],
  },
  {
    slug: "quan-short-kaki",
    name: "Quần short kaki",
    category: "Quần short",
    audience: "Unisex",
    price: 199000,
    image: "/images/placeholder.svg",
    hoverImage: "/images/placeholder.svg",
    isNew: true,
    rating: 0,
    reviews: 0,
    description: "Quần short kaki - hàng thiết kế, chất liệu kaki.",
    details: [
      "Chất liệu: Kaki",
      "Thương hiệu: Phương Lê",
      "Có size: S, M, L, XL",
      "Màu: Đen, Trắng, Be",
    ],
    colors: [
      {"name":"Đen","hex":"#1c1714"},
      {"name":"Trắng","hex":"#f0e7d8"},
      {"name":"Be","hex":"#d8c4a4"},
    ],
    sizes: ["S","M","L","XL"],
    variants: [
      {"id":"73","color":"Đen","size":"S","stock":27},
      {"id":"74","color":"Trắng","size":"S","stock":20},
      {"id":"75","color":"Be","size":"S","stock":21},
      {"id":"76","color":"Đen","size":"M","stock":13},
      {"id":"77","color":"Trắng","size":"M","stock":20},
      {"id":"78","color":"Be","size":"M","stock":20},
      {"id":"79","color":"Đen","size":"L","stock":10},
      {"id":"80","color":"Trắng","size":"L","stock":17},
      {"id":"81","color":"Be","size":"L","stock":23},
      {"id":"82","color":"Đen","size":"XL","stock":9},
      {"id":"83","color":"Trắng","size":"XL","stock":26},
      {"id":"84","color":"Be","size":"XL","stock":23},
    ],
  },
  {
    slug: "quan-tay-cong-so",
    name: "Quần tây công sở",
    category: "Quần tây",
    audience: "Unisex",
    price: 329000,
    image: "/images/placeholder.svg",
    hoverImage: "/images/placeholder.svg",
    isNew: true,
    rating: 0,
    reviews: 0,
    description: "Quần tây công sở - hàng thiết kế, chất liệu kaki.",
    details: [
      "Chất liệu: Kaki",
      "Thương hiệu: Phương Lê",
      "Có size: S, M, L, XL",
      "Màu: Đen, Trắng, Be",
    ],
    colors: [
      {"name":"Đen","hex":"#1c1714"},
      {"name":"Trắng","hex":"#f0e7d8"},
      {"name":"Be","hex":"#d8c4a4"},
    ],
    sizes: ["S","M","L","XL"],
    variants: [
      {"id":"61","color":"Đen","size":"S","stock":24},
      {"id":"62","color":"Trắng","size":"S","stock":20},
      {"id":"63","color":"Be","size":"S","stock":10},
      {"id":"64","color":"Đen","size":"M","stock":21},
      {"id":"65","color":"Trắng","size":"M","stock":14},
      {"id":"66","color":"Be","size":"M","stock":0},
      {"id":"67","color":"Đen","size":"L","stock":15},
      {"id":"68","color":"Trắng","size":"L","stock":13},
      {"id":"69","color":"Be","size":"L","stock":26},
      {"id":"70","color":"Đen","size":"XL","stock":19},
      {"id":"71","color":"Trắng","size":"XL","stock":8},
      {"id":"72","color":"Be","size":"XL","stock":22},
    ],
  },
  {
    slug: "tui-tote-canvas",
    name: "Túi tote canvas",
    category: "Túi xách",
    audience: "Unisex",
    price: 139000,
    image: "/images/placeholder.svg",
    hoverImage: "/images/placeholder.svg",
    isNew: true,
    rating: 0,
    reviews: 0,
    description: "Túi tote canvas - hàng thiết kế, chất liệu canvas.",
    details: [
      "Chất liệu: Canvas",
      "Thương hiệu: Phương Lê",
      "Có size: S, M, L, XL",
      "Màu: Đen, Trắng, Be",
    ],
    colors: [
      {"name":"Đen","hex":"#1c1714"},
      {"name":"Trắng","hex":"#f0e7d8"},
      {"name":"Be","hex":"#d8c4a4"},
    ],
    sizes: ["S","M","L","XL"],
    variants: [
      {"id":"109","color":"Đen","size":"S","stock":0},
      {"id":"110","color":"Trắng","size":"S","stock":29},
      {"id":"111","color":"Be","size":"S","stock":11},
      {"id":"112","color":"Đen","size":"M","stock":27},
      {"id":"113","color":"Trắng","size":"M","stock":20},
      {"id":"114","color":"Be","size":"M","stock":28},
      {"id":"115","color":"Đen","size":"L","stock":3},
      {"id":"116","color":"Trắng","size":"L","stock":5},
      {"id":"117","color":"Be","size":"L","stock":4},
      {"id":"118","color":"Đen","size":"XL","stock":23},
      {"id":"119","color":"Trắng","size":"XL","stock":4},
      {"id":"120","color":"Be","size":"XL","stock":7},
    ],
  },
  {
    slug: "vay-ngan-xep-ly",
    name: "Váy ngắn xếp ly",
    category: "Váy ngắn",
    audience: "Unisex",
    price: 279000,
    image: "/images/placeholder.svg",
    hoverImage: "/images/placeholder.svg",
    isNew: true,
    rating: 0,
    reviews: 0,
    description: "Váy ngắn xếp ly - hàng thiết kế, chất liệu voan.",
    details: [
      "Chất liệu: Voan",
      "Thương hiệu: Phương Lê",
      "Có size: S, M, L, XL",
      "Màu: Đen, Trắng, Be",
    ],
    colors: [
      {"name":"Đen","hex":"#1c1714"},
      {"name":"Trắng","hex":"#f0e7d8"},
      {"name":"Be","hex":"#d8c4a4"},
    ],
    sizes: ["S","M","L","XL"],
    variants: [
      {"id":"85","color":"Đen","size":"S","stock":16},
      {"id":"86","color":"Trắng","size":"S","stock":22},
      {"id":"87","color":"Be","size":"S","stock":19},
      {"id":"88","color":"Đen","size":"M","stock":29},
      {"id":"89","color":"Trắng","size":"M","stock":29},
      {"id":"90","color":"Be","size":"M","stock":23},
      {"id":"91","color":"Đen","size":"L","stock":19},
      {"id":"92","color":"Trắng","size":"L","stock":12},
      {"id":"93","color":"Be","size":"L","stock":5},
      {"id":"94","color":"Đen","size":"XL","stock":18},
      {"id":"95","color":"Trắng","size":"XL","stock":30},
      {"id":"96","color":"Be","size":"XL","stock":0},
    ],
  },
];

/** Danh mục con thật của shop, xếp theo số sản phẩm giảm dần. */
export const shopeeCategories: Array<{ name: string; count: number }> = [
  { name: "Áo thun", count: 2 },
  { name: "Áo sơ mi", count: 1 },
  { name: "Váy ngắn", count: 1 },
  { name: "Túi xách", count: 1 },
  { name: "Quần jean", count: 1 },
  { name: "Quần tây", count: 1 },
  { name: "Đầm dự tiệc", count: 1 },
  { name: "Áo khoác", count: 1 },
  { name: "Quần short", count: 1 },
];

/**
 * Danh mục gốc, dùng cho các ô "Mua theo danh mục" ở trang chủ.
 * count là tổng sản phẩm của cả nhánh (gốc + các danh mục con).
 */
export const rootCategories: Array<{
  name: string;
  slug: string;
  image: string | null;
  count: number;
  children: string[];
}> = [
  { name: "Áo", slug: "ao", image: null, count: 4, children: ["Áo sơ mi","Áo thun","Áo khoác"] },
  { name: "Quần", slug: "quan", image: null, count: 3, children: ["Quần jean","Quần tây","Quần short"] },
  { name: "Váy - Đầm", slug: "vay-dam", image: null, count: 2, children: ["Váy ngắn","Đầm dự tiệc"] },
  { name: "Phụ kiện", slug: "phu-kien", image: null, count: 1, children: ["Túi xách","Thắt lưng"] },
];

/** để README / trang quản trị biết dữ liệu lấy lúc nào */
export const importedAt: string | null = "2026-08-17T20:26:30+07:00";
